#!/bin/bash

# Location of logfile
LOGFILE="/var/log/synchwclock.log"

if [ ! -f $LOGFILE ]; then
  touch $LOGFILE
fi

#check Debian Version - HWCLOCK is in different locations depending on version + not necessarily in PATH
# --debug has been depricated as well, replace with --verbose in Debian 10
case `cat /etc/debian_version` in
	9*) hwclockPath="/sbin/"
		hwclockVerbose="--debug"
		;;
	10*) hwclockPath="/usr/sbin/"
		hwclockVerbose="--verbose"
		;;
	*)  hwclockPath=""
		hwClockVerbose="--debug"	
		;;
esac


# Set the maximum allowed difference in seconds between Hw-Clock and Sys-Clock
maxDiffSec="1"

msgNoConnection="No connection to time-server"
msgConnection="Connection to time-server"

echo $(date)": Starting Check" >> $LOGFILE

# Check for NTP connection
if ( ntpq -p | grep -q "^*"  ); then
        echo $msgConnection
        echo "---------------------------------"

        secHwClock=$(${hwclockPath}hwclock ${hwclockVerbose} | grep "^Hw clock time" | awk '{print $(NF-3)}')
        echo "HwClock: $secHwClock sec"

        secSysClock=$(date +"%s")
        echo "SysClock: $secSysClock sec"
        echo "---------------------------------"

        secDiff=$(($secHwClock-$secSysClock))

        # Compute absolute value
        if ( echo $secDiff | grep -q "-" ); then
            secDiff=$(echo $secDiff | cut -d "-" -f 2)
        fi

        echo "Difference: $secDiff sec"
		echo "Difference: $secDiff sec" >> $LOGFILE

        msgDiff="HwClock difference: $secDiff sec"
        if [ "$secDiff" -gt "$maxDiffSec" ] ; then
                echo "---------------------------------"
                echo "The difference between Hw- and Sys-Clock is more than $maxDiffSec sec."
                echo "Hw-Clock will be updated"

                # Update hwclock from system clock
                ${hwclockPath}hwclock -w
                msgDiff="$msgDiff --> HW-Clock updated."
        fi
        if !(awk '/./{line=$0} END{print line}' $LOGFILE | grep -q "$msgConnection") || [ "$secDiff" -gt "$maxDiffSec" ]; then
                echo $(date)": "$msgConnection". "$msgDiff >> $LOGFILE
        fi
else
        # No NTP connection
        echo $msgNoConnection
        if !(awk '/./{line=$0} END{print line}' $LOGFILE | grep -q "$msgNoConnection"); then
                echo $(date)": $msgNoConnection" >> $LOGFILE
        fi
fi